### PR TITLE
Add outbox import

### PR DESCRIPTION
**Pull request by angusmcleod**
@pmusaraj This is the most basic version of the import of prior activities of a new follow (i.e. "outbox import"). As discussed, it's a rake task. I've added two rake tasks actually. I'll give some notes on each.

### activity_pub:import_outbox
This is the import task. The arguments are:
- Actor (handle, ap_Id, or id): this is the actor who will received the imported activities (i.e. a category where the imported posts will appear).
- Target Actor (handle, ap_Id, or id): this is the actor from whom the activities are being imported from. The Actor has to be following the Target Actor to import their outbox.
- Log type (optional: "warn"): The AP logger has been set up to give print descriptive logs about what's going on to stdout, in addition to its normal logging. The default log type is "info", which will print info or error messages to stdout. It will not print process warnings (e.g. see below)

#### Example
```
rake "activity_pub:import_outbox[general@angus.ngrok.io,general@angus.thepavilion.io]"
```
This will import activities in outbox of `general@angus.thepavilion.io`, the AP handle of a category on one Discourse ("Discourse 1") on my local, to `general@angus.ngrok.io`, the AP handle of a category on another Discourse ("Discourse 2") on my local. This is what it looks like.

Screenshot 2024-02-21 at 15 21 50

The table you're seeing that is the "info" printout you'll see if any new activities are imported, giving you a snapshot of the object that have been created. It's the same function as the `activity_pub:info` task (see below) uses.

It only imported 4 out of 48 activities in the outbox because the other 44 already existed on Discourse 2. I ran the same command again, but with the log level set to "warn", and this was the result.

Screenshot 2024-02-21 at 15 22 54

With the log level set to "warn" I am now seeing why all 48 activities are not being imported the second time it's being run: the activities have already been imported.

### activity_pub:info
Given an ActivityPub ID (e.g. `https://mastodon.pavilion.tech/users/angus/statuses/111432292558317535/activity`) this will tell you whether the AP object exists on this server, what kind of object it is and what Discourse objects it's connected to. This can be useful for debugging purposes, as the ActivityPub ID is typically what is added to logged warnings or errors.

#### Example
I go to import the outbox of my mastodon account, which I've just re-followed.
```
rake "activity_pub:import_outbox[general@angus.ngrok.io,angus@mastodon.pavilion.tech,warn]"
```
I get this result
Screenshot 2024-02-21 at 16 14 46

I can use the `info` task to see more about my local record of the activities that have already been imported.

Screenshot 2024-02-21 at 16 16 03

### Next steps

I say this is the the most basic version as, even though it works in the way I've described above, there's still work to be done on this during this phase, specifically I'll be adding:

1. Collection pagination to the collections we serialize from our outboxes.
2. Proper handling of pagination in collection processing (Mastodon paginates their outboxes, and currently we're not handling that properly).
3. Pre-processing filtering of previously imported activities, i.e. it will be significantly more efficient to just filter out the previously imported activities in a single query rather than validate (and reject) each one.

Specifically, this basic version is only properly tested with Discourse to Discourse outbox imports. I'm giving this to you now as it does work for that use case, it'll give you a chance to test and request changes, and I'm trying to avoid big PRs.

### CODE REVIEW

**Comment by pmusaraj** [comment]
Thanks @angusmcleod, I have been testing this locally, and having a very hard time getting it to work with a category on meta. I can post details later, but can you try this with https://meta.discourse.org/ap/category/125/followers locally?

**Comment by angusmcleod** [comment]
@pmusaraj The issue is that `moderators-docs@meta.discourse.org` only has three activities in its outbox and all of them are Follows / Accepts. This means that there aren't any previously published activities to import. For context, this is how I saw that. First, I attempted an import, with the log level set to "warn".

Screenshot 2024-02-22 at 11 43 27

3 activities to process means there were 3 items in that actor's outbox. To learn more about each activity I use the info task. I've just added remote support to that to make it more useful. Profiling the first on the list, the previously processed one, I see it's an accept of my own follow of that category (of which I have a local copy)

Screenshot 2024-02-22 at 11 47 57

Profiling the second on the list, I see it's also an accept of a follow. It will be one of the accepts for the two other follows for that category, as will the last activity in the outbox. I wouldn't expect (or need) my local to have a copy of those activities.

Screenshot 2024-02-22 at 11 48 13

If you're hoping to import the existing topics in that category, they'll need to be published first. This task is for previously published topics which you don't already have (e.g. which were published prior to you following the actor). It's the rake version of this item in the spec in the "Import" section.

> Add a per-actor action in the “Followed” UI to import previously published activities of the Followed actor.
> - This is done by GETing prior activities from the Actor’s Outbox.
> - For Mastodon Actors this means importing “First Posts” (i.e. not replies) of the Actor.
> - For Discourse Group Actors (Categories (and maybe tags)) this will mean importing all previous announcements of activities in that group’s outbox.

There'll be a separate task to bulk-publish existing topics, i.e. this item in the "Publish" section of the Phase 4 spec

> Add a rake task to schedule publication of topics by category id or list of topic ids.

There are a few ways we could do this. My current thinking is that we'll make them available in the outbox (i.e. create activities for the existing content), but not push them out directly to all followers, or at least put that behaviour behind a setting. Bulk publishing a bunch of existing content from a category would be a bit spammy. Once they're added to the outbox, you'd then be able to import them.

**Comment by angusmcleod** [comment]
@pmusaraj I'm leaving this in draft to let you continue to test, however I've already mostly finished an improved version alongside an bulk publish library / task, i.e. this

>There'll be a separate task to bulk-publish existing topics, i.e. this item in the "Publish" section of the Phase 4 spec
>>Add a rake task to schedule publication of topics by category id or list of topic ids.

I'll make a PR for the combined task set this coming week.

**Comment by pmusaraj** [comment]
Ok, thanks @angusmcleod. Happy to go with whatever process you like. If it's best to switch to the next PR and close this one, that's good with me.

**Pull request closed without merging**
